---
title: "Covid-19 interactive map of infected people using R"
author: "Fernando Greve"
date: "2/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
map = "https://raw.githubusercontent.com/fgreve/d3-comunas-cl/master/data/comunas.json"
stgo <- geojsonio::geojson_read(map, what = "sp")
class(stgo)
```


```{r}
names(stgo)
```

```{r}
# That object is made of 5 "slots"
slotNames(stgo)
```

```{r}
class(stgo@polygons)
```


```{r}
# Each polygon is itself a list with 5 slots (incl. all the vertice coordinates).
slotNames(stgo@polygons[[1]])
```

```{r}
# We can access each slot (using "@")
class(stgo@data)
```

```{r}
data = stgo@data
```

```{r}
library(dplyr) # tidyverse
library(tidyr) # gather()

minsal = read.csv("https://raw.githubusercontent.com/MinCiencia/Datos-COVID19/master/output/producto1/Covid-19.csv", 
              check.names = FALSE,
              encoding="UTF-8") %>% 
  rename(cod_reg="Codigo region",id="Codigo comuna")

```



```{r}
stgo = sp::merge(stgo, minsal, by = "id")
```


```{r}
class(stgo)
```

```{r}
stgo <- stgo[!is.na(stgo@data$Region),]
```

```{r}
stgo <- stgo[stgo@data$Region=="Metropolitana",]
```


```{r}
no_stgo = c("Tiltil","Lampa","Colina","San Jose de Maipo","Pirque","Paine","Buin","Alhue","Melipilla","San Pedro","Maria Pinto","Curacavi","Penaflor","Calera de Tango","Padre Hurtado","El Monte","Talagante","Isla de Maipo","Lo Barnechea")

stgo = stgo[!(stgo@data$Comuna %in% no_stgo),]

```


```{r}
data = stgo@data
```


```{r}
library(leaflet)
m <- leaflet(stgo) %>%
  setView(lng = -70.64724, lat = -33.47269, zoom = 11) %>%
  addProviderTiles("MapBox", options = providerTileOptions(
    id = "mapbox.light",
    accessToken = Sys.getenv('MAPBOX_ACCESS_TOKEN')))

m %>% addPolygons()

```



```{r}
m %>% addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)
)
```



```{r}
bins <- c(400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000, Inf)
pal <- colorBin("YlOrRd", domain = stgo$Tasa, bins = bins)

m %>% addPolygons(
  fillColor = ~pal(Tasa),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7)


```


```{r}
m %>% addPolygons(
  fillColor = ~pal(Tasa),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE))
```


```{r}
labels <- sprintf(
  "<strong>%s</strong><br/>%g infected / population",
  stgo$Comuna, stgo$Tasa
) %>% lapply(htmltools::HTML)

m <- m %>% addPolygons(
  fillColor = ~pal(Tasa),
  weight = 2,
  opacity = 1,
  color = "white",
  dashArray = "3",
  fillOpacity = 0.7,
  highlight = highlightOptions(
    weight = 5,
    color = "#666",
    dashArray = "",
    fillOpacity = 0.7,
    bringToFront = TRUE),
  label = labels,
  labelOptions = labelOptions(
    style = list("font-weight" = "normal", padding = "3px 8px"),
    textsize = "15px",
    direction = "auto"))
m
```


```{r}
m %>% addLegend(pal = pal, values = ~Tasa, opacity = 0.7, title = NULL,
  position = "bottomright")
```











