library("dplyr")
library("shiny")

load("VotosSenado.Rda")

function(input, output) {
  datasetInput <- reactive({
    switch(input$dataset,
           "TODOS" = head(select(filter(VotosSenado, grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),           
           #"Walker P. Ignacio" = head(select(filter(VotosSenado, Senador_name=="Walker_P_Patricio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Allamand Z. Andres"=head(select(filter(VotosSenado, Senador_name=="Allamand_Z_Andres", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Alvear V. Soledad"=head(select(filter(VotosSenado, Senador_name=="Alvear_V_Soledad", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Arancibia R. Jorge"=head(select(filter(VotosSenado, Senador_name=="Arancibia_R_Jorge", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Avila C. Nelson"=head(select(filter(VotosSenado, Senador_name=="Avila_C_Nelson", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Cantero O. Carlos"=head(select(filter(VotosSenado, Senador_name=="Cantero_O_Carlos", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Chadwick P. Andres"=head(select(filter(VotosSenado, Senador_name=="Chadwick_P_Andres", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Coloma C. Juan Antonio"=head(select(filter(VotosSenado, Senador_name=="Coloma_C_Juan_Antonio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Escalona M. Camilo"=head(select(filter(VotosSenado, Senador_name=="Escalona_M_Camilo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Espina O. Alberto"=head(select(filter(VotosSenado, Senador_name=="Espina_O_Alberto", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Flores L. Fernando"=head(select(filter(VotosSenado, Senador_name=="Flores_L_Fernando", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Frei R. Eduardo"=head(select(filter(VotosSenado, Senador_name=="Frei_R_Eduardo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Garcia R. Jose"=head(select(filter(VotosSenado, Senador_name=="Garcia_R_Jose", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Gazmuri M. Jaime"=head(select(filter(VotosSenado, Senador_name=="Gazmuri_M_Jaime", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Girardi L. Guido"=head(select(filter(VotosSenado, Senador_name=="Girardi_L_Guido", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Gomez U. Jose Antonio"=head(select(filter(VotosSenado, Senador_name=="Gomez_U_Jose_Antonio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Horvath K. Antonio"=head(select(filter(VotosSenado, Senador_name=="Horvath_K_Antonio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Kuschel S. Carlos Ignacio"=head(select(filter(VotosSenado, Senador_name=="Kuschel_S_Carlos_Ignacio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Larrain F. Hernan"=head(select(filter(VotosSenado, Senador_name=="Larrain_F_Hernan", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Longueira M. Pablo"=head(select(filter(VotosSenado, Senador_name=="Longueira_M_Pablo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Matthei F. Evelyn"=head(select(filter(VotosSenado, Senador_name=="Matthei_F_Evelyn", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Munoz A. Pedro"=head(select(filter(VotosSenado, Senador_name=="Munoz_A_Pedro", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Munoz B. Roberto"=head(select(filter(VotosSenado, Senador_name=="Munoz_B_Roberto", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Novoa V. Jovino"=head(select(filter(VotosSenado, Senador_name=="Novoa_V_Jovino", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Ominami P. Carlos"=head(select(filter(VotosSenado, Senador_name=="Ominami_P_Carlos", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Orpis B. Jaime"=head(select(filter(VotosSenado, Senador_name=="Orpis_B_Jaime", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Prokurica P. Baldo"=head(select(filter(VotosSenado, Senador_name=="Prokurica_P_Baldo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Ruiz-Esquide J. Mariano"=head(select(filter(VotosSenado, Senador_name=="Ruiz-Esquide_J_Mariano", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Sabag C. Hosain"=head(select(filter(VotosSenado, Senador_name=="Sabag_C_Hosain", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Vasquez U. Guillermo"=head(select(filter(VotosSenado, Senador_name=="Vasquez_U_Guillermo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Zaldivar L. Adolfo"=head(select(filter(VotosSenado, Senador_name=="Zaldivar_L_Adolfo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Perez V. Victor"=head(select(filter(VotosSenado, Senador_name=="Perez_V_Victor", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Bianchi C. Carlos"=head(select(filter(VotosSenado, Senador_name=="Bianchi_C_Carlos", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Letelier M. Juan Pablo"=head(select(filter(VotosSenado, Senador_name=="Letelier_M_Juan_Pablo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Romero P. Sergio"=head(select(filter(VotosSenado, Senador_name=="Romero_P_Sergio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Naranjo O. Jaime"=head(select(filter(VotosSenado, Senador_name=="Naranjo_O_Jaime", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Navarro B. Alejandro"=head(select(filter(VotosSenado, Senador_name=="Navarro_B_Alejandro", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Nunez M. Ricardo"=head(select(filter(VotosSenado, Senador_name=="Nunez_M_Ricardo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Pizarro S. Jorge"=head(select(filter(VotosSenado, Senador_name=="Pizarro_S_Jorge", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Allende B. Isabel"=head(select(filter(VotosSenado, Senador_name=="Allende_B_Isabel", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Chahuan C. Francisco"=head(select(filter(VotosSenado, Senador_name=="Chahuan_C_Francisco", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Garcia Huidobro S. Alejandro"=head(select(filter(VotosSenado, Senador_name=="Garcia_Huidobro_S_Alejandro", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Lagos W. Ricardo"=head(select(filter(VotosSenado, Senador_name=="Lagos_W_Ricardo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Rincon G. Ximena"=head(select(filter(VotosSenado, Senador_name=="Rincon_G_Ximena", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Rossi C. Fulvio"=head(select(filter(VotosSenado, Senador_name=="Rossi_C_Fulvio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Tuma Z. Eugenio"=head(select(filter(VotosSenado, Senador_name=="Tuma_Z_Eugenio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Uriarte H. Gonzalo"=head(select(filter(VotosSenado, Senador_name=="Uriarte_H_Gonzalo", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Von Baer J. Ena"=head(select(filter(VotosSenado, Senador_name=="Von_Baer_J_Ena", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Walker P. Patricio"=head(select(filter(VotosSenado, Senador_name=="Walker_P_Patricio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Zaldivar L. Andres"=head(select(filter(VotosSenado, Senador_name=="Zaldivar_L_Andres", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Walker P. Ignacio"=head(select(filter(VotosSenado, Senador_name=="Walker_P_Ignacio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Perez S. Lily"=head(select(filter(VotosSenado, Senador_name=="Perez_S_Lily", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Quintana L. Jaime"=head(select(filter(VotosSenado, Senador_name=="Quintana_L_Jaime", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Larrain P. Carlos"=head(select(filter(VotosSenado, Senador_name=="Larrain_P_Carlos", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Araya G. Pedro"=head(select(filter(VotosSenado, Senador_name=="Araya_G_Pedro", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "De Urresti L. Alfonso"=head(select(filter(VotosSenado, Senador_name=="De_Urresti_L_Alfonso", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Goic B. Carolina"=head(select(filter(VotosSenado, Senador_name=="Goic_B_Carolina", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Harboe B. Felipe"=head(select(filter(VotosSenado, Senador_name=="Harboe_B_Felipe", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Montes C. Carlos"=head(select(filter(VotosSenado, Senador_name=="Montes_C_Carlos", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Moreira B. Ivan"=head(select(filter(VotosSenado, Senador_name=="Moreira_B_Ivan", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Munoz D. Adriana"=head(select(filter(VotosSenado, Senador_name=="Munoz_D_Adriana", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Guillier A. Alejandro"=head(select(filter(VotosSenado, Senador_name=="Guillier_A_Alejandro", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Ossandon I. Manuel Jose"=head(select(filter(VotosSenado, Senador_name=="Ossandon_I_Manuel_Jose", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Van Rysselberghe H. Jacqueline"=head(select(filter(VotosSenado, Senador_name=="Van_Rysselberghe_H_Jacqueline", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Quinteros L. Rabindranath"=head(select(filter(VotosSenado, Senador_name=="Quinteros_L_Rabindranath", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100),
           "Matta A. Manuel Antonio"=head(select(filter(VotosSenado, Senador_name=="Matta_A_Manuel_Antonio", grepl(input$txt, Tema, ignore.case=TRUE), fecha >= input$dateRange[1], fecha <= input$dateRange[2] ),Senador, Tema, Voto, fecha, Sesion, Legislatura),100))
  })
  
  output$table <- renderTable({
    datasetInput()
  })
  
  
}